import React from "react";

function HomePagePortfolioImages() {
  return (
    <div className={"desktop-only"}>
      <div className={"max-container py-10"}>
        <div className={"heading--2 flex flex-row justify-end text-grey"}>
          <span className={"cursor-pointer text-black hover:text-black"}>
            (ALL)
          </span>
          ,<span className={"cursor-pointer hover:text-black"}>ECOMMERCE</span>,
          <span className={"cursor-pointer hover:text-black"}>BRANDING</span>,
          <span className={"cursor-pointer hover:text-black"}>DIGITAL</span>,
          <span className={"cursor-pointer hover:text-black"}>PRODUCT</span>
        </div>
      </div>

      <div className={"mb-20 flex flex-row items-start overflow-hidden"}>
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-1.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-2.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-3.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-2.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-1.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-3.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-2.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-1.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-2.png"
          alt="sample-1"
        />

        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-3.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-2.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-1.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-3.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-2.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-3.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-1.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-3.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-2.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-3.png"
          alt="sample-1"
        />
      </div>
      <div className={"mb-20 flex flex-row items-start overflow-hidden"}>
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-1.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-2.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-3.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-2.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-1.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-3.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-2.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-1.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-2.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-3.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-2.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-1.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-3.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-2.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-1.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-3.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-2.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-1.png"
          alt="sample-1"
        />
      </div>
      <div className={"mb-64 flex flex-row items-start overflow-hidden"}>
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-1.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-2.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-3.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-2.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-1.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-3.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-2.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-1.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-2.png"
          alt="sample-1"
        />

        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-3.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-2.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-1.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-3.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-2.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-3.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-1.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-3.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-2.png"
          alt="sample-1"
        />
        <img
          className={"object-contain"}
          width={"90"}
          height={"auto"}
          src="/img/sample/portfolio-3.png"
          alt="sample-1"
        />
      </div>
    </div>
  );
}

export default HomePagePortfolioImages;
